### ISSUE TITLE
[FRONTEND] - Mogućnost stvaranje vlastite igre i obrazac za isto (na dashboardu registriranih korisnika)

### ISSUE THREAD

**Issue by vito-vrbic** [vito-vrbic/Nat20Mappers#29]
Potrebno je dodati mogućnost slanja nekakvog obrasca, komunicirati s backendom oko toga što sve taj obrazac treba i može sadržavati i kako će se slati (koji path). Nakon komunikacije oko načina slanja, implementirati mogućnost stvaranja igre za korisnike na frontendu (profilu korisnika koji je registriran).

**Comment by PatrickKlicek** [comment]
Napravio sam granu na kojoj sam stavio formu gdje korisnik na svojem dashboardu može kreirati igru. Sa Lukom sam prošao što bi igra trebala sva imati, odnosno što bi sve trebalo biti u toj formi, te smo došli do zaključka da bi trebalo provjeriti sa backendom ima li razlike između applicationRequired i requiresForm jer u bazi podataka ima samo requires_form, dok u klasi igra postoji i requiresForm i applicationRequired (Za sad je oboje ostavljeno u formi). Također sam dodao mali POST u server.js da provjerim jel se ispravno dodaju igre i pronađu li se ispravno u search. Što se tice same "custom" forme koje korisnik stvori ako izabere requiresForm nije implementirano jer treba porazgovarati za backendom kako ce to izgledati (a i sam neznam kako bi to na frontendu izveo).

**Comment by PatrickKlicek** [comment]
Postavio update gdje se sada privatnog korisnika prisliti da applicationRequired bude true kada želi stvoriti lokalnu igru, te sam dodao mogucnost stavljanja svojih pitanja za korisnike koji ce se htjeti prodružiti igri. Odvojio sam Form css od Dashboard css i malo uredio obecnito form css.
