### ISSUE TITLE
Frontend - Navbar

### ISSUE THREAD

**Issue by vito-vrbic** [vito-vrbic/Nat20Mappers#3]
Urediti Navbar.jsx koji će se nalaziti na svim stranicama. Već je stavljen da se nalazi na svim stranicama, ali ga treba urediti.

**Comment by MaksHiz** [comment]
Testing - Navbar (No. 1)

Navbar je implementiran funkcionalno sa strane frontenda. Za različite korisnike ima različite kategorije prikazane kao što i treba te logout gumb nas odjavi iz stranice. Privremeno ću postaviti ovaj problem kao razriješen. Ubuduće se možda ponovo otvori ovisno o novim zahtjevima ili u slučaju ako će postojati potreba za promjenom dizajna.
